# Generated by Django 5.1.6 on 2025-10-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topicshare_shareaccess_peerrelationship'),
    ]

    operations = [
    ]
