# Generated by Django 5.1.6 on 2025-10-21 11:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20251013_0016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='progress',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='peerrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='peerrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='topicshare',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='topicshare',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['topic', 'starred'], name='api_card_topic_i_f90cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['topic', 'progress'], name='api_card_topic_i_f90884_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['topic', '-created_at'], name='api_card_topic_i_35cb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='peerrelationship',
            index=models.Index(fields=['requester', 'status'], name='api_peerrel_request_083944_idx'),
        ),
        migrations.AddIndex(
            model_name='peerrelationship',
            index=models.Index(fields=['addressee', 'status'], name='api_peerrel_address_47ce3a_idx'),
        ),
        migrations.AddIndex(
            model_name='peerrelationship',
            index=models.Index(fields=['status', '-created_at'], name='api_peerrel_status_f7d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['user', '-created_at'], name='api_topic_user_id_8cabb6_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['user', 'name'], name='api_topic_user_id_bf4c02_idx'),
        ),
        migrations.AddIndex(
            model_name='topicshare',
            index=models.Index(fields=['peer', 'is_active'], name='api_topicsh_peer_id_e85348_idx'),
        ),
        migrations.AddIndex(
            model_name='topicshare',
            index=models.Index(fields=['owner', '-shared_at'], name='api_topicsh_owner_i_d29965_idx'),
        ),
        migrations.AddIndex(
            model_name='topicshare',
            index=models.Index(fields=['topic', 'is_active'], name='api_topicsh_topic_i_a15cb2_idx'),
        ),
    ]
